pokedex = {
	{name = "Bulbasaur",},
	{name = "Ivysaur"},
	{name = "Venusaur"},
	{name = "Charmander"},
	{name = "Charmeleon"},
	{name = "Charizard"},
	{name = "Squirtle"},
	{name = "Wartortle"},
	{name = "Blastoise"},
	{name = "Caterpie"},
	{name = "Metapod"},
	{name = "Butterfree"},
	{name = "Weedle"},
	{name = "Kakuna"},
	{name = "Beedrill"},
}